title: DocIntel Docs
email: antoine@docintel.org
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for DocIntel
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: docintelapp
github_username:  docintelapp

# Build settings
theme: "just-the-docs"
plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red